"""Generates real, buildable project files: a Forge/Fabric Java mod source zip and a
Bedrock .mcaddon (behavior + resource pack)."""
from __future__ import annotations

import io
import json
import uuid
import zipfile

from models.schemas import ModSpec

MC_VERSION = "1.20.1"
PKG_ROOT = "com.modcraft"


def _title(identifier: str) -> str:
    return " ".join(w.capitalize() for w in identifier.split("_"))


def _camel(identifier: str) -> str:
    return "".join(w.capitalize() for w in identifier.split("_"))


# --------------------------------------------------------------------------- Java
def _java_main(spec: ModSpec, loader: str) -> str:
    mid = spec.mod_id
    cls = _camel(mid)
    items = "\n".join(
        f'    public static final RegistryObject<Item> {i.identifier.upper()} = ITEMS.register("{i.identifier}",\n'
        f'            () -> new Item(new Item.Properties().stacksTo({max(1, min(64, i.stack_size))})));'
        for i in spec.items
    )
    gear = "\n".join(
        f'    public static final RegistryObject<Item> {g.identifier.upper()} = ITEMS.register("{g.identifier}",\n'
        f'            () -> new Item(new Item.Properties().durability({max(1, g.durability)})));'
        for g in spec.gear
    )
    blocks = "\n".join(
        f'    public static final RegistryObject<Block> {b.identifier.upper()} = BLOCKS.register("{b.identifier}",\n'
        f'            () -> new Block(BlockBehaviour.Properties.of()'
        f'.strength({b.hardness}F, {b.resistance}F).lightLevel(s -> {int(b.light_level)})));\n'
        f'    public static final RegistryObject<Item> {b.identifier.upper()}_ITEM = ITEMS.register("{b.identifier}",\n'
        f'            () -> new BlockItem({b.identifier.upper()}.get(), new Item.Properties()));'
        for b in spec.blocks
    )
    ores = "\n".join(
        f'    public static final RegistryObject<Block> {o.identifier.upper()} = BLOCKS.register("{o.identifier}",\n'
        f'            () -> new Block(BlockBehaviour.Properties.of().strength(3.0F, 3.0F).requiresCorrectToolForDrops()));\n'
        f'    public static final RegistryObject<Item> {o.identifier.upper()}_ITEM = ITEMS.register("{o.identifier}",\n'
        f'            () -> new BlockItem({o.identifier.upper()}.get(), new Item.Properties()));'
        for o in spec.ores
    )
    return f"""package {PKG_ROOT}.{mid};

import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.CreativeModeTabs;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

/**
 * {spec.mod_name} — generated by ModCraft Studio for Minecraft {MC_VERSION} ({loader}).
 * {spec.description}
 */
@Mod({cls}Mod.MOD_ID)
public class {cls}Mod {{
    public static final String MOD_ID = "{mid}";

    public static final DeferredRegister<Item> ITEMS =
            DeferredRegister.create(ForgeRegistries.ITEMS, MOD_ID);
    public static final DeferredRegister<Block> BLOCKS =
            DeferredRegister.create(ForgeRegistries.BLOCKS, MOD_ID);
    public static final DeferredRegister<CreativeModeTab> TABS =
            DeferredRegister.create(net.minecraft.core.registries.Registries.CREATIVE_MODE_TAB, MOD_ID);

{items}

{gear}

{blocks}

{ores}

    public static final RegistryObject<CreativeModeTab> MAIN_TAB = TABS.register("{mid}_tab",
            () -> CreativeModeTab.builder()
                    .title(net.minecraft.network.chat.Component.translatable("itemGroup.{mid}"))
                    .icon(() -> new net.minecraft.world.item.ItemStack(
                            ITEMS.getEntries().stream().findFirst()
                                 .map(RegistryObject::get).orElse(net.minecraft.world.item.Items.STONE)))
                    .displayItems((params, output) ->
                            ITEMS.getEntries().forEach(e -> output.accept(e.get())))
                    .build());

    public {cls}Mod() {{
        IEventBus bus = FMLJavaModLoadingContext.get().getModEventBus();
        ITEMS.register(bus);
        BLOCKS.register(bus);
        TABS.register(bus);
    }}
}}
"""


def _mods_toml(spec: ModSpec) -> str:
    return f"""modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="{spec.mod_id}"
version="1.0.0"
displayName="{spec.mod_name}"
description='''
{spec.description}
'''

[[dependencies.{spec.mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.{spec.mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[{MC_VERSION}]"
    ordering="NONE"
    side="BOTH"
"""


def _build_gradle(spec: ModSpec) -> str:
    return f"""plugins {{
    id 'eclipse'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}}

version = '1.0.0'
group = '{PKG_ROOT}.{spec.mod_id}'
archivesBaseName = '{spec.mod_id}'

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {{
    mappings channel: 'official', version: '{MC_VERSION}'
    runs {{
        client {{ workingDirectory project.file('run') }}
        server {{ workingDirectory project.file('run') }}
    }}
}}

dependencies {{
    minecraft 'net.minecraftforge:forge:{MC_VERSION}-47.2.0'
}}

jar {{
    manifest {{ attributes(["Specification-Title": "{spec.mod_id}"]) }}
}}
"""


def _lang(spec: ModSpec) -> dict:
    lang = {f"itemGroup.{spec.mod_id}": spec.creative_tab or spec.mod_name}
    for i in spec.items:
        lang[f"item.{spec.mod_id}.{i.identifier}"] = i.name
    for g in spec.gear:
        lang[f"item.{spec.mod_id}.{g.identifier}"] = g.name
    for b in spec.blocks:
        lang[f"block.{spec.mod_id}.{b.identifier}"] = b.name
    for o in spec.ores:
        lang[f"block.{spec.mod_id}.{o.identifier}"] = o.name
    for m in spec.mobs:
        lang[f"entity.{spec.mod_id}.{m.identifier}"] = m.name
    return lang


def _recipe_json(spec: ModSpec, r) -> dict:
    def ns(identifier: str) -> str:
        return identifier if ":" in identifier else f"{spec.mod_id}:{identifier}"

    if r.type == "smelting":
        ing = r.ingredients[0] if r.ingredients else "minecraft:cobblestone"
        return {
            "type": "minecraft:smelting",
            "ingredient": {"item": ns(ing)},
            "result": ns(r.result_identifier),
            "experience": 0.7,
            "cookingtime": 200,
        }
    if r.type == "shapeless":
        return {
            "type": "minecraft:crafting_shapeless",
            "ingredients": [{"item": ns(i)} for i in (r.ingredients or ["minecraft:stick"])],
            "result": {"item": ns(r.result_identifier), "count": r.result_count},
        }
    return {
        "type": "minecraft:crafting_shaped",
        "pattern": r.pattern,
        "key": {k: {"item": ns(v)} for k, v in r.key.items()},
        "result": {"item": ns(r.result_identifier), "count": r.result_count},
    }


def build_java_zip(spec: ModSpec, loader: str = "forge") -> bytes:
    mid = spec.mod_id
    cls = _camel(mid)
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        root = f"{mid}/"
        z.writestr(root + "build.gradle", _build_gradle(spec))
        z.writestr(root + "settings.gradle", "pluginManagement {\n    repositories {\n        gradlePluginPortal()\n        maven { url = 'https://maven.minecraftforge.net/' }\n    }\n}\n")
        z.writestr(root + "gradle.properties", "org.gradle.jvmargs=-Xmx3G\norg.gradle.daemon=false\n")
        z.writestr(root + "README.md", _java_readme(spec, loader))
        src = f"{root}src/main/java/{PKG_ROOT.replace('.', '/')}/{mid}/"
        z.writestr(src + f"{cls}Mod.java", _java_main(spec, loader))
        res = f"{root}src/main/resources/"
        z.writestr(res + "META-INF/mods.toml", _mods_toml(spec))
        z.writestr(res + "pack.mcmeta", json.dumps({"pack": {"description": spec.mod_name, "pack_format": 15}}, indent=2))
        z.writestr(f"{res}assets/{mid}/lang/en_us.json", json.dumps(_lang(spec), indent=2))
        for i in spec.items:
            z.writestr(
                f"{res}assets/{mid}/models/item/{i.identifier}.json",
                json.dumps({"parent": "item/generated", "textures": {"layer0": f"{mid}:item/{i.identifier}"}}, indent=2),
            )
        for g in spec.gear:
            z.writestr(
                f"{res}assets/{mid}/models/item/{g.identifier}.json",
                json.dumps({"parent": "item/handheld", "textures": {"layer0": f"{mid}:item/{g.identifier}"}}, indent=2),
            )
        for b in list(spec.blocks) + list(spec.ores):
            z.writestr(
                f"{res}assets/{mid}/blockstates/{b.identifier}.json",
                json.dumps({"variants": {"": {"model": f"{mid}:block/{b.identifier}"}}}, indent=2),
            )
            z.writestr(
                f"{res}assets/{mid}/models/block/{b.identifier}.json",
                json.dumps({"parent": "block/cube_all", "textures": {"all": f"{mid}:block/{b.identifier}"}}, indent=2),
            )
            z.writestr(
                f"{res}assets/{mid}/models/item/{b.identifier}.json",
                json.dumps({"parent": f"{mid}:block/{b.identifier}"}, indent=2),
            )
            z.writestr(
                f"{res}data/{mid}/loot_tables/blocks/{b.identifier}.json",
                json.dumps(
                    {
                        "type": "minecraft:block",
                        "pools": [
                            {
                                "rolls": 1,
                                "entries": [{"type": "minecraft:item", "name": f"{mid}:{getattr(b, 'drop_identifier', '') or b.identifier}"}],
                            }
                        ],
                    },
                    indent=2,
                ),
            )
        for idx, r in enumerate(spec.recipes):
            z.writestr(
                f"{res}data/{mid}/recipes/{r.result_identifier}_{idx}.json",
                json.dumps(_recipe_json(spec, r), indent=2),
            )
        for o in spec.ores:
            z.writestr(
                f"{res}data/{mid}/worldgen/configured_feature/{o.identifier}.json",
                json.dumps(
                    {
                        "type": "minecraft:ore",
                        "config": {
                            "size": o.vein_size,
                            "discard_chance_on_air_exposure": 0.0,
                            "targets": [
                                {
                                    "target": {"predicate_type": "minecraft:tag_match", "tag": "minecraft:stone_ore_replaceables"},
                                    "state": {"Name": f"{mid}:{o.identifier}"},
                                }
                            ],
                        },
                    },
                    indent=2,
                ),
            )
            z.writestr(
                f"{res}data/{mid}/worldgen/placed_feature/{o.identifier}.json",
                json.dumps(
                    {
                        "feature": f"{mid}:{o.identifier}",
                        "placement": [
                            {"type": "minecraft:count", "count": o.veins_per_chunk},
                            {"type": "minecraft:in_square"},
                            {
                                "type": "minecraft:height_range",
                                "height": {
                                    "type": "minecraft:uniform",
                                    "min_inclusive": {"absolute": o.min_y},
                                    "max_inclusive": {"absolute": o.max_y},
                                },
                            },
                            {"type": "minecraft:biome"},
                        ],
                    },
                    indent=2,
                ),
            )
        z.writestr(root + "TEXTURES.md", _texture_guide(spec))
    return buf.getvalue()


def _java_readme(spec: ModSpec, loader: str) -> str:
    return f"""# {spec.mod_name}

{spec.description}

Generated by **ModCraft Studio** — Minecraft {MC_VERSION}, {loader.capitalize()} loader.

## Build

```bash
./gradlew build          # jar lands in build/libs/
./gradlew runClient      # launch a dev client
```

Requires JDK 17.

## Contents
- Items: {len(spec.items)}
- Blocks: {len(spec.blocks)}
- Recipes: {len(spec.recipes)}
- Mobs: {len(spec.mobs)}
- Tools/Armor: {len(spec.gear)}
- Ores (with world generation): {len(spec.ores)}

See `TEXTURES.md` for the 16x16 PNG files to drop in.
"""


def _texture_guide(spec: ModSpec) -> str:
    lines = ["# Textures to add (16x16 PNG)\n"]
    for i in list(spec.items) + list(spec.gear):
        lines.append(f"- `assets/{spec.mod_id}/textures/item/{i.identifier}.png` — {getattr(i, 'texture_hint', '') or i.name}")
    for b in list(spec.blocks) + list(spec.ores):
        lines.append(f"- `assets/{spec.mod_id}/textures/block/{b.identifier}.png` — {getattr(b, 'texture_hint', '') or b.name}")
    return "\n".join(lines) + "\n"


# ------------------------------------------------------------------------ Bedrock
def build_bedrock_pack(spec: ModSpec) -> bytes:
    mid = spec.mod_id
    fmt = [2, 0, 0]
    bp_uuid, bp_mod_uuid = str(uuid.uuid4()), str(uuid.uuid4())
    rp_uuid, rp_mod_uuid = str(uuid.uuid4()), str(uuid.uuid4())
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        bp, rp = f"{mid}_BP/", f"{mid}_RP/"
        z.writestr(
            bp + "manifest.json",
            json.dumps(
                {
                    "format_version": 2,
                    "header": {"name": f"{spec.mod_name} BP", "description": spec.description,
                               "uuid": bp_uuid, "version": [1, 0, 0], "min_engine_version": [1, 20, 0]},
                    "modules": [{"type": "data", "uuid": bp_mod_uuid, "version": [1, 0, 0]}],
                    "dependencies": [{"uuid": rp_uuid, "version": [1, 0, 0]}],
                },
                indent=2,
            ),
        )
        z.writestr(
            rp + "manifest.json",
            json.dumps(
                {
                    "format_version": 2,
                    "header": {"name": f"{spec.mod_name} RP", "description": spec.description,
                               "uuid": rp_uuid, "version": [1, 0, 0], "min_engine_version": [1, 20, 0]},
                    "modules": [{"type": "resources", "uuid": rp_mod_uuid, "version": [1, 0, 0]}],
                },
                indent=2,
            ),
        )
        for i in spec.items:
            z.writestr(
                f"{bp}items/{i.identifier}.json",
                json.dumps(
                    {
                        "format_version": "1.20.10",
                        "minecraft:item": {
                            "description": {"identifier": f"{mid}:{i.identifier}", "menu_category": {"category": "items", "group": f"{mid}:{mid}_group"}},
                            "components": {
                                "minecraft:max_stack_size": max(1, min(64, i.stack_size)),
                                "minecraft:icon": {"texture": i.identifier},
                                "minecraft:display_name": {"value": i.name},
                            },
                        },
                    },
                    indent=2,
                ),
            )
        for g in spec.gear:
            z.writestr(
                f"{bp}items/{g.identifier}.json",
                json.dumps(
                    {
                        "format_version": "1.20.10",
                        "minecraft:item": {
                            "description": {"identifier": f"{mid}:{g.identifier}", "menu_category": {"category": "equipment"}},
                            "components": {
                                "minecraft:durability": {"max_durability": max(1, g.durability)},
                                "minecraft:damage": g.damage,
                                "minecraft:icon": {"texture": g.identifier},
                                "minecraft:display_name": {"value": g.name},
                            },
                        },
                    },
                    indent=2,
                ),
            )
        for b in list(spec.blocks) + list(spec.ores):
            z.writestr(
                f"{bp}blocks/{b.identifier}.json",
                json.dumps(
                    {
                        "format_version": "1.20.10",
                        "minecraft:block": {
                            "description": {"identifier": f"{mid}:{b.identifier}", "menu_category": {"category": "construction"}},
                            "components": {
                                "minecraft:destructible_by_mining": {"seconds_to_destroy": float(getattr(b, "hardness", 3.0))},
                                "minecraft:destructible_by_explosion": {"explosion_resistance": float(getattr(b, "resistance", 3.0))},
                                "minecraft:light_emission": int(getattr(b, "light_level", 0)),
                                "minecraft:material_instances": {"*": {"texture": b.identifier, "render_method": "opaque"}},
                            },
                        },
                    },
                    indent=2,
                ),
            )
        for m in spec.mobs:
            z.writestr(
                f"{bp}entities/{m.identifier}.json",
                json.dumps(
                    {
                        "format_version": "1.20.10",
                        "minecraft:entity": {
                            "description": {"identifier": f"{mid}:{m.identifier}", "is_spawnable": True, "is_summonable": True},
                            "components": {
                                "minecraft:health": {"value": m.health, "max": m.health},
                                "minecraft:movement": {"value": m.movement_speed},
                                "minecraft:attack": {"damage": m.attack_damage},
                                "minecraft:physics": {},
                                "minecraft:behavior.random_stroll": {"priority": 6, "speed_multiplier": 1.0},
                                **({"minecraft:behavior.melee_attack": {"priority": 3}} if m.hostile else {}),
                            },
                        },
                    },
                    indent=2,
                ),
            )
        for idx, r in enumerate(spec.recipes):
            if r.type == "smelting":
                data = {
                    "format_version": "1.20.10",
                    "minecraft:recipe_furnace": {
                        "description": {"identifier": f"{mid}:{r.result_identifier}_{idx}"},
                        "tags": ["furnace"],
                        "input": (r.ingredients[0] if r.ingredients else "minecraft:cobblestone"),
                        "output": f"{mid}:{r.result_identifier}",
                    },
                }
            elif r.type == "shapeless":
                data = {
                    "format_version": "1.20.10",
                    "minecraft:recipe_shapeless": {
                        "description": {"identifier": f"{mid}:{r.result_identifier}_{idx}"},
                        "tags": ["crafting_table"],
                        "ingredients": [{"item": i if ":" in i else f"{mid}:{i}"} for i in (r.ingredients or ["minecraft:stick"])],
                        "result": {"item": f"{mid}:{r.result_identifier}", "count": r.result_count},
                    },
                }
            else:
                data = {
                    "format_version": "1.20.10",
                    "minecraft:recipe_shaped": {
                        "description": {"identifier": f"{mid}:{r.result_identifier}_{idx}"},
                        "tags": ["crafting_table"],
                        "pattern": r.pattern,
                        "key": {k: {"item": v if ":" in v else f"{mid}:{v}"} for k, v in r.key.items()},
                        "result": {"item": f"{mid}:{r.result_identifier}", "count": r.result_count},
                    },
                }
            z.writestr(f"{bp}recipes/{r.result_identifier}_{idx}.json", json.dumps(data, indent=2))
        texts = {f"item.{mid}:{i.identifier}.name": i.name for i in spec.items}
        texts.update({f"tile.{mid}:{b.identifier}.name": b.name for b in list(spec.blocks) + list(spec.ores)})
        texts.update({f"entity.{mid}:{m.identifier}.name": m.name for m in spec.mobs})
        z.writestr(rp + "texts/en_US.lang", "\n".join(f"{k}={v}" for k, v in texts.items()) + "\n")
        z.writestr(
            rp + "textures/item_texture.json",
            json.dumps(
                {
                    "resource_pack_name": mid,
                    "texture_name": "atlas.items",
                    "texture_data": {i.identifier: {"textures": f"textures/items/{i.identifier}"} for i in list(spec.items) + list(spec.gear)},
                },
                indent=2,
            ),
        )
        z.writestr(
            rp + "textures/terrain_texture.json",
            json.dumps(
                {
                    "resource_pack_name": mid,
                    "texture_name": "atlas.terrain",
                    "padding": 8,
                    "num_mip_levels": 4,
                    "texture_data": {b.identifier: {"textures": f"textures/blocks/{b.identifier}"} for b in list(spec.blocks) + list(spec.ores)},
                },
                indent=2,
            ),
        )
        z.writestr(
            "README.md",
            f"# {spec.mod_name} — Bedrock Addon\n\nDouble-click this file to import into Minecraft Bedrock, "
            f"or unzip `{mid}_BP` into `behavior_packs/` and `{mid}_RP` into `resource_packs/`.\n\n"
            f"Format version {'.'.join(map(str, fmt))}. Add 16x16 PNGs under `{mid}_RP/textures/items|blocks/`.\n",
        )
    return buf.getvalue()
